name: publish and deploy demo
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      # 下载源码
    - name: Checkout
      uses: actions/checkout@master

      # 打包构建
    - name: Build
    - run: npm i
    - run: npm run build
    - run: tar -zcvf release.tgz .nuxt static nuxt.config.js package.json package-lock.json

      # 发布release
    - name: create release
      id: create_release
      uses: actions/create-release@master
      envv:
        GITHUB_TOKEN: ${{ screts.TOKEN1 }}
      with:
        tag_name: ${{ github.ref }}
        release_name: release ${{ github.ref }}
        draft: false
        prerelease: false

      # 上传构建结果到 release
    - name: upload release asset
       id: upload-release-asset
       uses: actions/upload-release-asset@master
       env:
         GITHUB_TOKEN: ${{ screts.TOKEN1 }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./release.tgz
         asset_name: release.tgz
         asset_content_type: application/x-tgz

      # 部署到服务器
    - name: deploy
      uses: appleboy/ssh-action@master

